// any app specific constants that you don't want to keep in config can go here.
export const SYSTEM_ERROR = "System error. Please try again later!";
export const CTA_YES = "Yes";
export const CTA_NO = "No";
export const CTA_CANCEL = "Cancel";
export const PALETTE_COLOR = {
    TOP_GRAY: '#E7ECF4',
    ACCENT_GREEN: '#86D971',
    ACCENT_GREEN_LIGHT: '#8FE579',
    ACCENT_PURPLE: '#8989FF',
    ACCENT_PURPLE_LIGHT: '#9999FF',
    ACCENT_RED: '#FF5555',
    ACCENT_RED_LIGHT: '#FF6F6F',
    ACCENT_ORANGE: "#FF7C32",
    ACCENT_ORANGE_LIGHT: '#FF9153',
    MAIN_BLUE: '#457AFB',
    MAIN_WHITE: '#FFFFFF',
    MAIN_GREEN: '#3DD771',
    MIDDLE_GRAY: '#6D737B',
    LIGHT_GREY: '#878E97',
    FIELD_BORDER_COLOR: '#E7ECF4',
    BLACK: '#000000',
    INACTIVE_GRAY: '#999999',
    ACTIVE_STATUS_BACKGROUND: 'rgba(134, 217, 113, 0.2)',
    INVITED_STATUS_BACKGROUND: 'rgba(137, 137, 255, 0.2)',
    DRAFT_STATUS_BACKGROUND: 'rgba(172, 172, 172, 0.2)',
    BLOCKED_STATUS_BACKGROUND: 'rgba(255, 157, 86, 0.2)',
    ARCHIVED_STATUS_BACKGROUND: 'rgba(255, 85, 85, 0.2)',
    TEXT_ORANGE: '#FF9D56',
    BACKGROUND_BlUE: '#E6F0FF',
    FIELD_COLOR: '#EFF4FB',
    INACTIVE_GREY_BLUE: '#B4C0CF',
    FIELD_BORDER_ERROR: '#FFACAC',
    AVATAR_LIGHT_BLUE: '#E4ECF7',
    AVATAR_PURPLE: '#8484FF',
    AVATAR_GREEN: '#A6EB8E',
    AVATAR_ORANGE: '#FFC9A1',
    AVATAR_YELLOW: '#FFCD4C',
    AVATAR_PINK: '#FFBAF8',
    AVATAR_BLUE: '#5BD9FF'
}
